objects/APIIntegration__mdt.object
<CustomObject>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTTPMethod__c</fullName>
        <label>HTTP Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                    <default>true</default>
                    <label>GET</label>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>PATCH</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestBody__c</fullName>
        <description>Key:Value pairs to be sent in the JSON. Each entry should be added on a new line with static strings enclosed between double quotes.</description>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RequestHeaders__c</fullName>
        <description>Parameters to be set in the header. Each key:value pair on a new line</description>
        <inlineHelpText>Parameters to be set in the header. Each key:value pair on a new line</inlineHelpText>
        <label>Request Headers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Maximum time in seconds after which the request times out. Max possible value : 120000 (2 minutes)</description>
        <inlineHelpText>Maximum time in seconds after which the request times out. Max possible value : 120000 (2 minutes)</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>API Integration</label>
    <pluralLabel>API Integrations</pluralLabel>
</CustomObject>

force-app/main/default/classes/IntegrationUtility.cls
public with sharing class IntegrationUtility {

    private APIIntegration__mdt callout;
    public IntegrationUtility(String APIIntegrationName ) {
        this.callout = [SELECT Id, Endpoint__c, HTTPMethod__c, DeveloperName, RequestBody__c, RequestHeaders__c, Timeout__c 
                               FROM APIIntegration__mdt 
                               WHERE DeveloperName = :APIIntegrationName];
    }

    /**
    * @description Creates HTTPRequest with the basic information in API Integration metadata record without headers
    * @author Nitish Yadav | 03-28-2021 
    * @return HttpRequest 
    **/
    public HttpRequest getHTTPRequestWithoutHeaders(){
        HttpRequest request = new HttpRequest();
        request.setEndpoint(this.callout.Endpoint__c);
        request.setTimeout(Integer.valueOf(this.callout.Timeout__c));
        request.setMethod(this.callout.HTTPMethod__c);        
        return request;
    }

    /**
    * @description Creates HTTPRequest with the basic information in API Integration metadata record with headers
                   Specified in metadata record
    * @author Nitish Yadav | 03-28-2021 
    * @return HttpRequest 
    **/
    public HttpRequest getHTTPRequestWithHeaders(){
        HttpRequest request = new HttpRequest();
        request.setEndpoint(this.callout.Endpoint__c);
        request.setTimeout(Integer.valueOf(this.callout.Timeout__c));
        request.setMethod(this.callout.HTTPMethod__c);
        setRequestHeaders(request);
        return request;
    }

    /**
    * @description Builds the request body 
    * @author Nitish Yadav | 03-27-2021 
    * @param objectMap - Map of name used in request body and the corresponding record
    * @return Map<String,Object>
    **/
    public Map<String,Object> buildRequestBody(Map<String,SObject> objectMap){
        String requestString = this.callout.RequestBody__c;

        // Build the request map
        Map<String,Object> requestMap = new Map<String,Object>();
        for(String row : requestString.trim().split('\n')){
            String key = row.substringBefore(':').trim();
            String value = row.substringAfter(':').trim();
            System.debug('key : '+ key +', value : ' + value);
            List<String> tokens = value.split('\\.');
            if(value == 'null'){
                requestMap.put(key,null);
            }else if(value == 'true' || value == 'false'){
                requestMap.put(key,Boolean.valueOf(value));
            }else if(isNumber(value)){
                requestMap.put(key,Decimal.valueOf(value));
            }else if(Pattern.matches('DATETIME\\(.*\\)', value)){
                String dateFormat = value.substringBetween('(',')');
                requestMap.put(key, String.isBlank(dateFormat) ? DateTime.now().format() :  DateTime.now().format(dateFormat));
            }else if(value.startsWith('\"') && value.endsWith('\"')){
                requestMap.put(key,value.substringBetween('"'));
            }else if(value.contains('.') && tokens.size() == 2){
                requestMap.put(key,objectMap.get(tokens[0]).get(tokens[1]));
            }else if(value.contains('.') && tokens.size()==3){
                requestMap.put(key,objectMap.get(tokens[0]).getSObject(tokens[1]).get(tokens[2]));
            }
        }
        return requestMap;
    }

    /**
    * @description Sets the request headers for an HTTPRequest
    * @author Nitish Yadav | 03-27-2021 
    * @param request - Reference to HTTP Request for which headers are to be set
    **/
    public void setRequestHeaders(HttpRequest request){
        // Set the headers
        if(String.isNotBlank(this.callout.RequestHeaders__c)){
            for(String header : this.callout.RequestHeaders__c.trim().split('\n')){
                request.setHeader(header.substringBefore(':').trim(), header.substringAfter(':').trim());
            }
        }
    }
    
    private static Boolean isNumber(String input){
        Boolean returnValue;
        try{
            Decimal.valueOf(input);
            returnValue =  true;
        }catch(Exception ex){
            returnValue = false;
        }
        System.debug(input + ' isNumber : ' + returnValue);
        return returnValue;
    }
}